### ISSUE TITLE
'Hidden' function

### ISSUE THREAD

**Issue by Paul-Reed** [Steveorevo/node-red-contrib-credentials#1]
A very welcome addition to the pallet!
Works great, but just a little feedback about the 'hidden' function...

If the password is added and 'hidden' is selected, the password is hidden (expected!), but if you then change back from 'hidden' to 'string', the password is deleted.
I can see that this may be your desired result, but having just done this, it stopped my flow and took me 10 minutes to recover my password again!
I don't see the purpose in hiding it, because even if it's hidden, it's very easy to discover the password - just add a debug node and it will print in the debug pane.
So weighing up the pros & cons of having the hide function, I would much prefer the node without it, but that's only my personal opinion.

Thanks for sharing.

Paul

**Comment by Steveorevo** [comment]
Hi Paul. Yes, that's the intended function. Explained in the README.md. You can toggle back and forth unless you save; then it inhibits "seeing" it again once the panel is re-opened. It's also explained that you can extract it by simply using the DOM inspector or a debug node. Unfortunately the credentials API does not support arbitrary length arrays in password mode, otherwise we'd block all access except for runtime mode once a password is submitted. Currently it serializes everything and if we were to inhibit one password entry they would all have to be re-typed. The hide option is only intended for 'plain view' obfuscation. 

We're starting to do demos of flows in our Meetup groups and some are being recorded and streamed live; without hidden mode, things get a little awkward ;)

**Comment by Paul-Reed** [comment]
Is there a way to obfuscate/hide the field in the node without deleting the password - so users can switch from string to hidden, and back to string, without losing the password?
As I said, it's only my personal opinion, influenced by having to obtain new passwords & api keys after inadvertently losing them (after a deploy)!

**Comment by Steveorevo** [comment]
It will only delete if the value was saved as hidden. So re-opening the panel recalls if the original value was hidden to begin with; then the erase comes into play. Removing line 51 in credentials.html will prevent the behavior: 

```
                      $('#node-input-value-' + i).val('');
```

**Comment by Paul-Reed** [comment]
Thanks, but I prefer not to make local changes to nodes, because they can be overwritten when nodes get updated. I was hoping that you'd consider making that change in the published node.
If not, thanks anyway.

Paul
